name: üöÄ Deploy Hosekra Theme to cPanel via SFTP

on:
  push:
    branches:
      - main  # ali 'master', ƒçe uporablja≈° master

jobs:
  sftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy with SSH key
        uses: easingthemes/ssh-deploy@v2.2.11
        with:
          REMOTE_HOST: ${{ secrets.SFTP_SERVER }}
          REMOTE_USER: ${{ secrets.SFTP_USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.SFTP_PRIVATE_KEY }}
          TARGET: ${{ secrets.SFTP_REMOTE_PATH }}
          SOURCE: .
          ARGS: "-avz --delete --exclude=.git* --exclude=.github"
