name: üöÄ Deploy Hosekra Theme to cPanel via SFTP

on:
  push:
    branches:
      - main  # spremeni, ƒçe uporablja≈° drug branch

jobs:
  sftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: SFTP Deploy
        uses: pressidium/lftp-mirror-action@v1
        with:
          host: ${{ secrets.SFTP_SERVER }}
          port: 22
          user: ${{ secrets.SFTP_USERNAME }}
          pass: ${{ secrets.SFTP_PASSWORD }}
          localDir: '.'  # Deploy celotno vsebino repozitorija
          remoteDir: '/public_html/alpenhomes/wp-content/themes/Hosekra-main/'
          options: '--exclude-glob .git* --exclude .github --only-newer'

